version: '3'
services:
  server:
    container_name: nginx
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - application
  application:
    container_name: app
    build: ./php
    volumes:
      - ./src:/var/www/html
    depends_on:
      - database

 
  database:
    container_name: db
    restart: always
    build: ./mysql
    volumes:
    - mysql_data:/var/lib/mysql
    env_file:
      - ./mysql/.env
    ports:
      - 3308:3306
volumes:
  mysql_data: