<?php
    define('ROOT', dirname(__DIR__));
    define('APP', ROOT.DIRECTORY_SEPARATOR.'app');
    define('VIEW', ROOT.DIRECTORY_SEPARATOR.'app'.DIRECTORY_SEPARATOR.'Views'.DIRECTORY_SEPARATOR);
    define('INCLUDES', ROOT.DIRECTORY_SEPARATOR.'app'.DIRECTORY_SEPARATOR.'Includes'.DIRECTORY_SEPARATOR);
    define('HELPERS', ROOT.DIRECTORY_SEPARATOR.'app'.DIRECTORY_SEPARATOR.'Helpers'.DIRECTORY_SEPARATOR);
    define('STORAGE', ROOT.DIRECTORY_SEPARATOR.'storage'.DIRECTORY_SEPARATOR);